package com.nyora.hasan72341.shared

/// Runtime patches over the pinned `nyora-parsers-redo` dependency, whose source domains are
/// baked into the compiled JAR and cannot be edited in-tree. Mirrors the iOS port's in-tree fixes.
///
/// - [DOMAIN_OVERRIDES]: rebranded/relocated sources whose default domain is dead; the value is the
///   current live domain (curl-verified, or live-behind-Cloudflare). Applied via ConfigKey.Domain.
/// - [DEAD_SOURCES]: sources whose domain is dead with no working same-CMS successor; skipped when
///   seeding the built-in source catalogue so they don't appear to users.
/// Keyed by the upstream `MangaParserSource.name`.
object SourcePatches {
    val DOMAIN_OVERRIDES: Map<String, String> = mapOf(
        "ALTAYSCANS" to "witchscans.com",
        "ASTRASCANS" to "astracomic.com",
        "FLOWERMANGA" to "flowermangas.net",
        "MANGAGEZGINI" to "mangagezgini.online",
        "MANHUAUSS" to "manhua.us.com",
        "MHSCANS" to "mhscans.com",
        "ISEKAISCAN_EU" to "isekaiscan.top",
        "RUYAMANGA" to "ruyamanga2.com",
        "TRUYENTRANHFULL" to "truyentranhfull.vip",
        "MANGATILKISI" to "tilkiscans.com",
        "YAOIBAR" to "yaoibar.lol",
        "AINZSCANS" to "ainzscans.net",
        "DOCTRUYEN3Q" to "doctruyen3qhub.org",
        "YUGEN_MANGAS_ES" to "visualikigai.com",
        "LEITORDEMANGA" to "leitordemangas.com",
        "LILYUMFANSUB" to "lilyumfansub.pro",
        // NOTE (2026-07 health-probe triage): HIPERDEX/TOONILY_ME/POJOKMANGA/MANHWAX/MANHWADESU/
        // MANHWALAND_INK/NEATMANGA all "moved" but rebuilt on a NEW site structure — a pure domain
        // override 404s on the parser's expected paths / still returns empty. They need a parser
        // (selector/API) rewrite, not a domain swap, so they are deliberately NOT listed here.
    )

    /// Display-name overrides for sources that rebranded along with their domain move.
    val TITLE_OVERRIDES: Map<String, String> = mapOf(
        "ASTRASCANS" to "Astra Comic",
        "MANGATILKISI" to "Tilki Scans",
        "ISEKAISCAN_EU" to "IsekaiScan",
        "YUGEN_MANGAS_ES" to "Visual Ikigai",
        "TOONILY_ME" to "ToonDex", // rebranded toonily.me → toondex.io (native ToonDexExtensionService)
    )

    // Sources whose baked-in domain is dead (DNS-unresolvable / connection-refused /
    // parked / suspended) with no working same-CMS successor — hidden from the catalogue.
    // Curated + health-probed 2026-07-15 (Cloudflare-protected sources are intentionally KEPT).
    // Keyed by the upstream `MangaParserSource.name`.
    val DEAD_SOURCES: Set<String> = setOf(
        "ADONISFANSUB",
        "AIYUMANGASCANLATION",
        "ALCEASCAN",
        "ANCIENTCOMICS",
        "ANIMESAMA",
        "ANISA_MANGA",
        "ARABSDOUJIN",
        "ASUPANKOMIK",
        "ASURASCANS_US",
        "ATEMPORAL",
        "AYATOON",
        "BAKAMAN",
        "BANANA_MANGA",
        "BEETOON",
        "BIRDTOON",
        "BURNINGSCANS",
        "CABAREDOWATAME",
        "CARTELDEMANHWAS",
        "CATHARSISFANTASY",
        "CLOVERMANGA",
        "CMANGA",
        "COMIC21",
        "COMICARAB",
        "COMIZ",
        "COSMIC_SCANS",
        "CULTURESUBS",
        "DECCALSCANS",
        "DEMONSECT",
        "DISKUSSCAN",
        "DOUJINDESURIP",
        "DOUJINS",
        "DOUJINSHELL",
        "DRAGONMANGA",
        "DREAMSCAN",
        "EDSCANLATION",
        "ELEVENSCANLATOR",
        "ELITEMANGA",
        "ENLIGNEMANGA",
        "EPIKMAN",
        "EROMANHWA",
        "ETHERALRADIANCE",
        "FACTMANGA",
        "FECOMICC",
        "FIRESCANS",
        "FRANXXMANGAS",
        "FREEMANGA",
        "FREEMANGATOP",
        "FRSCANSCOM",
        "GALINHASAMURAI",
        "GHOSTFANSUB",
        "GMANGA",
        "GOURMETSCANS",
        "GRIMELEK",
        "GUNCEL_MANGA",
        "HAMTRUYEN",
        "HANGTRUYEN",
        "HENSEKAI",
        "HENTAI18VN",
        "HENTAITECA",
        "HENTAIVN",
        "HENTAIVNBUZZ",
        "HENTAIZ",
        "HENTAMAN",
        "HIKARISCAN",
        "HOIFANSUB",
        "ICHIROMANGA",
        "IMPARATORMANGA",
        "IMPERIOSCANS",
        "JELLYRING",
        "JIMANGA",
        "JPMANGAS",
        "KABUSMANGA",
        "KALANGO",
        "KEDI",
        "KISHISAN",
        "KOMIKGES",
        "KOMIKMAMA",
        "KOMIKSAN",
        "KORELISCANS",
        "KUMASCANS",
        "LADYESTELARSCAN",
        "LECTORUNM",
        "LEGENDSCANLATIONS",
        "LERMANGAONLINE",
        "LILYUMFANSUB",
        "LIMBOSCAN",
        "LMTOS",
        "LUGNICASCANS",
        "LUNARSCANS",
        "LUXMANGA",
        "MAFIAMANGA",
        "MANGA_MANHUA",
        "MANGA_SCAN",
        "MANGA1K",
        "MANGA4LIFE",
        "MANGAAY",
        "MANGACIM",
        "MANGACIX",
        "MANGACLASH",
        "MANGAEFENDISI",
        "MANGAGOJO",
        "MANGAHAUS",
        "MANGAID",
        "MANGAJINX",
        "MANGAJP",
        "MANGAKINGS",
        "MANGAKISS",
        "MANGAKOINU",
        "MANGALIVRE",
        "MANGAMATE",
        "MANGANANQUIM",
        "MANGANINJA",
        "MANGANOON",
        "MANGAOKUTR",
        "MANGAONELOVE",
        "MANGAONLINETEAM",
        "MANGAOWL_ONE",
        "MANGAOWLBLOG",
        "MANGAREADCO",
        "MANGAROSE",
        "MANGARUBY",
        "MANGASCHAN",
        "MANGASECT",
        "MANGASONLINE",
        "MANGASSCANS",
        "MANGASTORM",
        "MANGATERRA",
        "MANGATOP",
        "MANGATR",
        "MANGATX_GG",
        "MANGAYARO",
        "MANHUAES",
        "MANHUAGA",
        "MANHUAGOLD",
        "MANHUASCAN",
        "MANHUASY",
        "MANHWAKU",
        "MANHWALIST",
        "MANHWASCO",
        "MANJANOON",
        "MANJANOON_EN",
        "MASTERKOMIK",
        "MAXGSSCAN",
        "MMDAOS",
        "MONARCAMANGA",
        "MONZEEKOMIK",
        "MOONLOVERSSCAN",
        "MOONWITCHINLOVESCAN",
        "MURIMSCAN",
        "NABISCANS",
        "NEUMANGA",
        "NEWTRUYEN",
        "NGOMIK",
        "NHENTAIWORLD",
        "NIMEMOB",
        "NIRVANASCAN",
        "NORMOYUN",
        "NORTEROSE",
        "NOVELMIC",
        "NOVELSTOWN",
        "NVMANGA",
        "OIOIVN",
        "OTAKUSAN_EN",
        "OTAKUSAN_VI",
        "PIEDPIPERFANSUB",
        "PONYMANGA",
        "POPSMANGA",
        "PROJETOSCANLATOR",
        "PRUNUSSCANS",
        "PUSSYSUSSYTOONS",
        "RAIKISCAN",
        "RAINBOWFAIRYSCAN",
        "RAMAREADER",
        "RAWMANGA",
        "RAWXZ",
        "RAYSSCAN",
        "READCOMICONLINE",
        "READER_EVILFLOWERS",
        "REAPERCOMICS",
        "RHPLUSMANGA",
        "RIGHTDARKSCAN",
        "RIO2MANGANET",
        "ROGMANGAS",
        "RUAHAPCHANHDAY",
        "SAYTRUYENHAY",
        "SCANMANGA",
        "SCANSRAW",
        "SECTSCANS",
        "SEINAGI",
        "SEINEMANGA",
        "SHADOWXMANGA",
        "SHOOTINGSTARSCANS",
        "SIIKOMIK",
        "SILENCESCAN",
        "SITEMANGA",
        "SOBATMANKU",
        "SSREADING",
        "STKISSMANGABLOG",
        "SWEETSCAN",
        "TATAKAE_SCANS",
        "TAURUSMANGA",
        "TCBSCANSMANGA",
        "TECNOSCANN",
        "TECNOSCANS",
        "TEMPESTFANSUBNET",
        "TERRITORIOLEAL",
        "TIMENAIGHT",
        "TMOMANGA",
        "TOONILY_ME",
        "TRADUCCIONESAMISTOSAS",
        "TRUYENHENTAI18",
        "TUMANGAONLINE",
        "TYRANTSCANS",
        "VFSCAN",
        "VILLAINESSSCAN",
        "VIYAFANSUB",
        "WEBTOONTR",
        "WEEBDEX_DE",
        "WEEBDEX_EN",
        "WEEBDEX_ES",
        "WEEBDEX_FR",
        "WEEBDEX_IT",
        "WEEBDEX_JA",
        "WEEBDEX_KO",
        "WEEBDEX_PT",
        "WEEBDEX_RU",
        "WEEBDEX_ZH",
        "WINTERSCAN",
        "WITCOMICS",
        "YAOITR",
        "YDCOMICS",
        "YUBIKIRI",
        "YUMEKOMIK",
        "YURAMANGA",
        "YURINEKO",
        "ZANDYNOFANSUB",
        "ZENITHSCANS",
        "ZEVEP",
        "ZIN_MANGA_COM",
        "ZINCHANMANGA_NET",
        "ZINMANGA_CC",
        "ZINMANGA_MS",
        "ZSCANLATION",
    )
}
